from django.urls import path
from .views import (
    ProspectingDiscoverAPIView, ProspectingLeadsAPIView, ProspectingResetAPIView,
    ProblemSignalListCreateAPIView, ProblemSignalDetailAPIView,
    LeadDetailAPIView, LeadEvidenceAPIView, LeadSignalsAPIView,
    LeadContactsAPIView, LeadEnrichContextAPIView, LeadEnrichAPIView,
    LeadQualifyContextAPIView, LeadQualifyAPIView,
    LeadBuyingGroupContextAPIView, LeadBuyingGroupAPIView, LeadResearchAPIView,
    LeadRefreshAPIView, LeadIntelligenceAPIView,
    TargetListListCreateAPIView, TargetListDetailAPIView,
    LeadSalesGuidanceContextAPIView, LeadSalesGuidanceAPIView, CampaignEnrollmentAPIView,
    EmailSequenceListCreateAPIView, EmailMessageListCreateAPIView,
    EmailMessageSendAPIView, InboundReplyListCreateAPIView,
    LeadFeedbackAPIView, DashboardOverviewAPIView, DashboardSignalsAPIView,
    DashboardFunnelAPIView, DashboardOpportunitiesAPIView, LeadCRMSyncAPIView,
    ProspectingIntakeAPIView, ProspectingIntakeDetailAPIView, ProspectingIntakeParseAPIView,
    ProspectingIntakeClarifyAPIView, ProspectingIntakeSpecificationAPIView,
    ProspectingIntakeConfirmAPIView, ProspectingIntakeCancelAPIView,
    ProspectingDiscoverStatusAPIView,
    ProspectingCampaignListAPIView, ProspectingCampaignDetailAPIView,
    ProspectingCampaignLeadsAPIView, DiscoveryRunListAPIView,
    DiscoveryRunDetailAPIView, DiscoveryRunLeadsAPIView, DiscoveryRunLeadResearchAPIView,
    ProspectingCampaignLeadsAPIView, ProspectingCampaignDiscoverMoreAPIView,
    DiscoveryRunListAPIView,
    DiscoveryRunDetailAPIView, DiscoveryRunLeadsAPIView,
    DiscoveryRunTraceAPIView,
    WorkerStartAPIView, WorkerStopAPIView, WorkerStatusAPIView
)

urlpatterns = [
    path('discover/', ProspectingDiscoverAPIView.as_view(), name='prospecting-discover'),
    path('discover/<uuid:pk>/status/', ProspectingDiscoverStatusAPIView.as_view(), name='prospecting-discover-status'),
    path('discovery-runs/', DiscoveryRunListAPIView.as_view(), name='discovery-runs-list'),
    path('discovery-runs/<uuid:pk>/', DiscoveryRunDetailAPIView.as_view(), name='discovery-run-detail'),
    path('discovery-runs/<uuid:pk>/leads/', DiscoveryRunLeadsAPIView.as_view(), name='discovery-run-leads'),
    path('discovery-runs/<uuid:pk>/research/', DiscoveryRunLeadResearchAPIView.as_view(), name='discovery-run-research'),
    path('discovery-runs/<uuid:pk>/trace/', DiscoveryRunTraceAPIView.as_view(), name='discovery-run-trace'),
    path('intake/', ProspectingIntakeAPIView.as_view(), name='prospecting-intake-list-create'),
    path('intake/<uuid:pk>/', ProspectingIntakeDetailAPIView.as_view(), name='prospecting-intake-detail'),
    path('intake/<uuid:pk>/parse/', ProspectingIntakeParseAPIView.as_view(), name='prospecting-intake-parse'),
    path('intake/<uuid:pk>/clarify/', ProspectingIntakeClarifyAPIView.as_view(), name='prospecting-intake-clarify'),
    path('intake/<uuid:pk>/specification/', ProspectingIntakeSpecificationAPIView.as_view(), name='prospecting-intake-specification'),
    path('intake/<uuid:pk>/confirm/', ProspectingIntakeConfirmAPIView.as_view(), name='prospecting-intake-confirm'),
    path('intake/<uuid:pk>/cancel/', ProspectingIntakeCancelAPIView.as_view(), name='prospecting-intake-cancel'),
    path('leads/', ProspectingLeadsAPIView.as_view(), name='prospecting-leads'),
    path('leads/<uuid:pk>/', LeadDetailAPIView.as_view(), name='lead-detail'),
    path('leads/<uuid:pk>/evidence/', LeadEvidenceAPIView.as_view(), name='lead-evidence'),
    path('leads/<uuid:pk>/signals/', LeadSignalsAPIView.as_view(), name='lead-signals'),
    path('leads/<uuid:pk>/contacts/', LeadContactsAPIView.as_view(), name='lead-contacts'),
    path('leads/<uuid:pk>/enrich/context/', LeadEnrichContextAPIView.as_view(), name='lead-enrich-context'),
    path('leads/<uuid:pk>/enrich/', LeadEnrichAPIView.as_view(), name='lead-enrich'),
    path('leads/<uuid:pk>/qualify/context/', LeadQualifyContextAPIView.as_view(), name='lead-qualify-context'),
    path('leads/<uuid:pk>/qualify/', LeadQualifyAPIView.as_view(), name='lead-qualify'),
    path('leads/<uuid:pk>/buying-group/context/', LeadBuyingGroupContextAPIView.as_view(), name='lead-buying-group-context'),
    path('leads/<uuid:pk>/buying-group/', LeadBuyingGroupAPIView.as_view(), name='lead-buying-group'),
    path('leads/<uuid:pk>/research/', LeadResearchAPIView.as_view(), name='lead-research'),
    path('leads/<uuid:pk>/refresh/', LeadRefreshAPIView.as_view(), name='lead-refresh'),
    path('leads/<uuid:pk>/intelligence/', LeadIntelligenceAPIView.as_view(), name='lead-intelligence'),
    path('leads/<uuid:pk>/sales-guidance/context/', LeadSalesGuidanceContextAPIView.as_view(), name='lead-sales-guidance-context'),
    path('leads/<uuid:pk>/sales-guidance/', LeadSalesGuidanceAPIView.as_view(), name='lead-sales-guidance'),
    path('leads/<uuid:pk>/feedback/', LeadFeedbackAPIView.as_view(), name='lead-feedback'),
    path('leads/<uuid:pk>/sync-crm/', LeadCRMSyncAPIView.as_view(), name='lead-sync-crm'),
    path('lists/', TargetListListCreateAPIView.as_view(), name='target-lists-list'),
    path('lists/<uuid:pk>/', TargetListDetailAPIView.as_view(), name='target-lists-detail'),
    path('campaigns/enrollments/', CampaignEnrollmentAPIView.as_view(), name='campaign-enrollments'),
    path('campaigns/', ProspectingCampaignListAPIView.as_view(), name='prospecting-campaigns-list'),
    path('campaigns/<uuid:pk>/', ProspectingCampaignDetailAPIView.as_view(), name='prospecting-campaign-detail'),
    path('campaigns/<uuid:pk>/leads/', ProspectingCampaignLeadsAPIView.as_view(), name='prospecting-campaign-leads'),
    path('campaigns/<uuid:pk>/discover-more/', ProspectingCampaignDiscoverMoreAPIView.as_view(), name='prospecting-campaign-discover-more'),
    path('emails/sequences/', EmailSequenceListCreateAPIView.as_view(), name='email-sequences-list'),
    path('emails/messages/', EmailMessageListCreateAPIView.as_view(), name='email-messages-list'),
    path('emails/messages/<uuid:pk>/send/', EmailMessageSendAPIView.as_view(), name='email-messages-send'),
    path('emails/replies/', InboundReplyListCreateAPIView.as_view(), name='email-replies-list'),
    path('dashboard/overview/', DashboardOverviewAPIView.as_view(), name='dashboard-overview'),
    path('dashboard/signals/', DashboardSignalsAPIView.as_view(), name='dashboard-signals'),
    path('dashboard/funnel/', DashboardFunnelAPIView.as_view(), name='dashboard-funnel'),
    path('dashboard/opportunities/', DashboardOpportunitiesAPIView.as_view(), name='dashboard-opportunities'),
    path('reset/', ProspectingResetAPIView.as_view(), name='prospecting-reset'),
    path('signals/', ProblemSignalListCreateAPIView.as_view(), name='prospecting-signals-list'),
    path('signals/<uuid:pk>/', ProblemSignalDetailAPIView.as_view(), name='prospecting-signals-detail'),
    path('workers/start/', WorkerStartAPIView.as_view(), name='worker-start'),
    path('workers/stop/', WorkerStopAPIView.as_view(), name='worker-stop'),
    path('workers/status/', WorkerStatusAPIView.as_view(), name='worker-status'),
]
