# Generated by Django 6.0.6 on 2026-08-10 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks & Libraries'), ('databases', 'Databases & Storage'), ('cloud_devops', 'Cloud & DevOps'), ('ai_ml', 'AI & Machine Learning'), ('tools', 'Tools & Platforms'), ('concepts', 'Concepts & Architecture')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(default='Expert', max_length=50)),
                ('years_experience', models.IntegerField(default=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='knowledge_base.userprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('user_profile', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('architecture_notes', models.TextField(blank=True, null=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('impact_metrics', models.JSONField(default=list)),
                ('project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='knowledge_base.userprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalKnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Senior Software Engineer', max_length=255)),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('target_roles', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='knowledge_base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_text', models.TextField()),
                ('parsed_summary', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('ats_keywords', models.JSONField(default=list)),
                ('experience_years_required', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='knowledge_base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('bullet_points', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='knowledge_base.userprofile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperienceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='knowledge_base.experience')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_links', to='knowledge_base.project')),
            ],
            options={
                'unique_together': {('project', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='SkillExperienceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='knowledge_base.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_links', to='knowledge_base.skill')),
            ],
            options={
                'unique_together': {('skill', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='SkillProjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='knowledge_base.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='knowledge_base.skill')),
            ],
            options={
                'unique_together': {('skill', 'project')},
            },
        ),
    ]
