"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import json
import os
import sys


def _env_bool(name, default=False):
    return os.environ.get(name, "true" if default else "false").strip().lower() in {"true", "1", "yes"}


def _bounded_env_int(name, default, minimum, maximum):
    value = int(os.environ.get(name, str(default)))
    if value < minimum or value > maximum:
        raise ValueError(f"{name} must be between {minimum} and {maximum}.")
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
def load_env_file():
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, val = line.split('=', 1)
                    key = key.strip()
                    val = val.strip().strip("'").strip('"')
                    os.environ.setdefault(key, val)

load_env_file()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Local development remains convenient, but production must opt out explicitly
# and provide its own secret through the deployment secret manager.
DEBUG = _env_bool("DEBUG", True)
if DEBUG or "test" in sys.argv:
    # Local notebooks and tests may call sync ORM code from an event-loop thread.
    os.environ.setdefault("DJANGO_ALLOW_ASYNC_UNSAFE", "true")
else:
    os.environ.pop("DJANGO_ALLOW_ASYNC_UNSAFE", None)
_development_secret = 'django-insecure-qs+p#ex#4di*v=m6uqjim74r4a3r5ar&o*2^nk!n#8+1sivr3a'
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _development_secret if DEBUG else "")
if not DEBUG and not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY is required when DEBUG is false.")

# Allowed Hostnames
ALLOWED_HOSTS=[]
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0'] if DEBUG else []
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS is required when DEBUG is false.")

# CSRF Trusted Origins
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(",") if origin.strip()]

CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)
CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", DEBUG)
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]
CONTENT_STUDIO_FRONTEND_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in os.environ.get("CONTENT_STUDIO_FRONTEND_ORIGINS", "").split(",")
    if origin.strip()
]

SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_HTTPONLY = False
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", not DEBUG)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = _bounded_env_int("SECURE_HSTS_SECONDS", 0 if DEBUG else 31536000, 0, 63072000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_celery_beat',
    'channels',
    'llm',
    'knowledge_base',
    'prospecting',
    'integrations.instagram',
    'integrations.social',
    'integrations.linkedin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ── Django Unfold Admin UI Configuration ──────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "Content Studio",
    "SITE_HEADER": "Content Studio Admin",
    "SITE_SUBHEADER": "Content publishing and workspace management",
    "SITE_URL": "/",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Redis Configuration (Supports REDIS_URL for remote/production or REDIS_HOST for local)
REDIS_URL = os.environ.get("REDIS_URL", "").strip().strip("'").strip('"')
if REDIS_URL.startswith("REDIS_URL="):
    REDIS_URL = REDIS_URL[len("REDIS_URL="):].strip().strip("'").strip('"')

redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")

if REDIS_URL:
    channel_layer_hosts = [REDIS_URL]
    celery_broker = REDIS_URL
    celery_backend = REDIS_URL
    cache_location = REDIS_URL
else:
    channel_layer_hosts = [(redis_host, 6379)]
    celery_broker = f'redis://{redis_host}:6379/0'
    celery_backend = f'redis://{redis_host}:6379/0'
    cache_location = f'redis://{redis_host}:6379/1'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": channel_layer_hosts,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

if 'test' in sys.argv:
    from django.test import TestCase, TransactionTestCase
    TestCase.databases = {'default'}
    TransactionTestCase.databases = {'default'}
    
    from django.db.backends.signals import connection_created
    from django.dispatch import receiver
    
    @receiver(connection_created)
    def set_sqlite_wal(sender, connection, **kwargs):
        if connection.vendor == 'sqlite':
            with connection.cursor() as cursor:
                cursor.execute('PRAGMA journal_mode=WAL;')
                cursor.execute('PRAGMA synchronous=NORMAL;')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30000,
            }
        },
    }
else:
    database_url = os.environ.get("DATABASE_URL", "").strip().strip("'").strip('"')
    if database_url.startswith("DATABASE_URL="):
        database_url = database_url[len("DATABASE_URL="):].strip().strip("'").strip('"')

    if database_url:
        default_db_config = dj_database_url.parse(
            database_url,
            conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", 0)),
            ssl_require=os.environ.get("DB_SSL_REQUIRE", "False").lower() in ("true", "1", "yes") or "supabase" in database_url,
        )
    else:
        default_db_config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'aios_db'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5433'),
        }

    DATABASES = {
        'default': default_db_config,
    }

DATABASE_ROUTERS = []


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SOCIAL_MEDIA_PRIVATE_ROOT = Path(
    os.environ.get("SOCIAL_MEDIA_PRIVATE_ROOT", BASE_DIR / ".private_social_media")
)
SOCIAL_MEDIA_PUBLISH_ROOT = Path(
    os.environ.get("SOCIAL_MEDIA_PUBLISH_ROOT", MEDIA_ROOT)
)

# Cloudflare R2 persistent storage configuration
CLOUDFLARE_R2_BUCKET_NAME = os.environ.get("CLOUDFLARE_R2_BUCKET_NAME", "").strip()
CLOUDFLARE_R2_ACCESS_KEY_ID = os.environ.get("CLOUDFLARE_R2_ACCESS_KEY_ID", "").strip()
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.environ.get("CLOUDFLARE_R2_SECRET_ACCESS_KEY", "").strip()
CLOUDFLARE_R2_ACCOUNT_ID = (
    os.environ.get("CLOUDFLARE_R2_ACCOUNT_ID", "").strip()
    or os.environ.get("CLOUDFLARE_ACCOUNT_ID", "").strip()
)
CLOUDFLARE_R2_PUBLIC_URL = os.environ.get("CLOUDFLARE_R2_PUBLIC_URL", "").strip()

if CLOUDFLARE_R2_BUCKET_NAME and CLOUDFLARE_R2_ACCESS_KEY_ID and CLOUDFLARE_R2_SECRET_ACCESS_KEY and CLOUDFLARE_R2_ACCOUNT_ID:
    r2_endpoint = f"https://{CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
    r2_publish_options = {
        "access_key": CLOUDFLARE_R2_ACCESS_KEY_ID,
        "secret_key": CLOUDFLARE_R2_SECRET_ACCESS_KEY,
        "bucket_name": CLOUDFLARE_R2_BUCKET_NAME,
        "endpoint_url": r2_endpoint,
        "region_name": "auto",
        "signature_version": "s3v4",
        "file_overwrite": False,
        "default_acl": None,
        "querystring_auth": False,
    }
    if CLOUDFLARE_R2_PUBLIC_URL:
        clean_domain = CLOUDFLARE_R2_PUBLIC_URL.replace("https://", "").replace("http://", "").strip("/")
        r2_publish_options["custom_domain"] = clean_domain

    SOCIAL_MEDIA_PUBLISH_STORAGE_BACKEND = "storages.backends.s3.S3Storage"
    SOCIAL_MEDIA_PUBLISH_STORAGE_OPTIONS = r2_publish_options
    SOCIAL_MEDIA_PRIVATE_STORAGE_BACKEND = "storages.backends.s3.S3Storage"
    SOCIAL_MEDIA_PRIVATE_STORAGE_OPTIONS = {
        **r2_publish_options,
        "location": "private",
    }
else:
    SOCIAL_MEDIA_PRIVATE_STORAGE_BACKEND = os.environ.get(
        "SOCIAL_MEDIA_PRIVATE_STORAGE_BACKEND",
        "django.core.files.storage.FileSystemStorage",
    )
    SOCIAL_MEDIA_PUBLISH_STORAGE_BACKEND = os.environ.get(
        "SOCIAL_MEDIA_PUBLISH_STORAGE_BACKEND",
        "django.core.files.storage.FileSystemStorage",
    )
    SOCIAL_MEDIA_PRIVATE_STORAGE_OPTIONS = (
        {"location": str(SOCIAL_MEDIA_PRIVATE_ROOT)}
        if SOCIAL_MEDIA_PRIVATE_STORAGE_BACKEND == "django.core.files.storage.FileSystemStorage"
        else json.loads(os.environ.get("SOCIAL_MEDIA_PRIVATE_STORAGE_OPTIONS", "{}"))
    )
    SOCIAL_MEDIA_PUBLISH_STORAGE_OPTIONS = (
        {
            "location": str(SOCIAL_MEDIA_PUBLISH_ROOT),
            "base_url": MEDIA_URL,
        }
        if SOCIAL_MEDIA_PUBLISH_STORAGE_BACKEND == "django.core.files.storage.FileSystemStorage"
        else json.loads(os.environ.get("SOCIAL_MEDIA_PUBLISH_STORAGE_OPTIONS", "{}"))
    )

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "social_private": {
        "BACKEND": SOCIAL_MEDIA_PRIVATE_STORAGE_BACKEND,
        "OPTIONS": SOCIAL_MEDIA_PRIVATE_STORAGE_OPTIONS,
    },
    "social_publish": {
        "BACKEND": SOCIAL_MEDIA_PUBLISH_STORAGE_BACKEND,
        "OPTIONS": SOCIAL_MEDIA_PUBLISH_STORAGE_OPTIONS,
    },
}

_external_url_allowlist = [
    hostname.strip().lower()
    for hostname in os.environ.get("SOCIAL_MEDIA_EXTERNAL_URL_ALLOWLIST", "").split(",")
    if hostname.strip()
]
if CLOUDFLARE_R2_PUBLIC_URL:
    from urllib.parse import urlparse
    _r2_parsed = urlparse(CLOUDFLARE_R2_PUBLIC_URL if "://" in CLOUDFLARE_R2_PUBLIC_URL else f"https://{CLOUDFLARE_R2_PUBLIC_URL}")
    if _r2_parsed.hostname and _r2_parsed.hostname.lower() not in _external_url_allowlist:
        _external_url_allowlist.append(_r2_parsed.hostname.lower())
if CLOUDFLARE_R2_ACCOUNT_ID:
    _r2_s3_host = f"{CLOUDFLARE_R2_ACCOUNT_ID.lower()}.r2.cloudflarestorage.com"
    if _r2_s3_host not in _external_url_allowlist:
        _external_url_allowlist.append(_r2_s3_host)

SOCIAL_MEDIA_EXTERNAL_URL_ALLOWLIST = tuple(_external_url_allowlist)

DISCOVERY_TRACE_STRING_LIMIT = int(os.environ.get("DISCOVERY_TRACE_STRING_LIMIT", "100000"))

# Celery Settings
CELERY_BROKER_URL = celery_broker
CELERY_RESULT_BACKEND = celery_backend
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = (
    os.environ.get("CELERY_TASK_ALWAYS_EAGER", "False").lower() in ("true", "1", "yes")
    or ("test" in sys.argv)
)
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_BEAT_SCHEDULE = {
    'social-fill-content-queues': {
        'task': 'social.fill_content_queues',
    },
    'social-publish-due-posts': {
        'task': 'social.publish_due_jobs',
        'schedule': 60,
    },
    'social-sync-submitted-posts': {
        'task': 'social.reconcile_publish_jobs',
        'schedule': 5 * 60,
    },
    'social-refresh-post-metrics': {
        'task': 'social.refresh_post_metrics',
        'schedule': 60 * 60,
    },
}


# Cache backend (Redis) for distributed task locking
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": cache_location,
    }
}

# Standard logger configuration to stream info logs to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} [{name}]: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'prospecting': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'llm': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# REST Framework API Documentation
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Local/test-only compatibility escape hatch for the original anonymous
# LinkedIn Studio. Production requests must authenticate and resolve through a
# WorkspaceMembership. Set this explicitly to True only for local development.
_content_automation_bootstrap_requested = os.environ.get(
    "CONTENT_AUTOMATION_DEV_BOOTSTRAP",
    "true" if "test" in sys.argv else "false",
).lower() in ("true", "1", "yes")
CONTENT_AUTOMATION_DEV_BOOTSTRAP = _content_automation_bootstrap_requested and (
    DEBUG or "test" in sys.argv
)
CONTENT_AUTOMATION_ASSET_TOKEN_MAX_AGE_SECONDS = int(os.environ.get(
    "CONTENT_AUTOMATION_ASSET_TOKEN_MAX_AGE_SECONDS",
    str(30 * 24 * 60 * 60),
))

SPECTACULAR_SETTINGS = {
    'TITLE': 'Content Studio API',
    'DESCRIPTION': 'Content Studio API documentation.',
    'VERSION': '3.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Cap leads collected per discovery run
PROSPECTING_MAX_LEADS_PER_RUN = int(os.environ.get("PROSPECTING_MAX_LEADS_PER_RUN", 10))

# ── Instagram Integration Settings ──────────────────────────────────────────
INSTAGRAM_APP_ID = os.environ.get("INSTAGRAM_APP_ID", "")
INSTAGRAM_APP_SECRET = os.environ.get("INSTAGRAM_APP_SECRET", "")
INSTAGRAM_REDIRECT_URI = os.environ.get(
    "INSTAGRAM_REDIRECT_URI",
    "http://localhost:8000/api/v3/integrations/instagram/oauth/callback/"
)
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = os.environ.get("INSTAGRAM_WEBHOOK_VERIFY_TOKEN", "")
INSTAGRAM_GRAPH_API_VERSION = os.environ.get("INSTAGRAM_GRAPH_API_VERSION", "v21.0")
INSTAGRAM_TOKEN_ENCRYPTION_KEY = os.environ.get("INSTAGRAM_TOKEN_ENCRYPTION_KEY", "")
INSTAGRAM_HTTP_TIMEOUT_SECONDS = int(os.environ.get("INSTAGRAM_HTTP_TIMEOUT_SECONDS", "15"))
INSTAGRAM_MAX_RETRY_ATTEMPTS = int(os.environ.get("INSTAGRAM_MAX_RETRY_ATTEMPTS", "3"))

# ── LinkedIn Content Automation ─────────────────────────────────────────────
# Buffer is the preferred Company Page publisher. n8n is supported as a signed
# workflow handoff; it still needs either Buffer or an eligible LinkedIn app.
SOCIAL_PUBLISHER_DEFAULT = os.environ.get("SOCIAL_PUBLISHER_DEFAULT", "ZERNIO").strip().upper()
if SOCIAL_PUBLISHER_DEFAULT not in {"UPLOAD_POST", "ZERNIO"}:
    raise ValueError("SOCIAL_PUBLISHER_DEFAULT must be UPLOAD_POST or ZERNIO.")

BUFFER_API_URL = os.environ.get("BUFFER_API_URL", "https://api.buffer.com").strip()
BUFFER_API_KEY = os.environ.get("BUFFER_API_KEY", "").strip()
BUFFER_CHANNEL_ID = os.environ.get("BUFFER_CHANNEL_ID", "").strip()
N8N_LINKEDIN_WEBHOOK_URL = os.environ.get("N8N_LINKEDIN_WEBHOOK_URL", "").strip()
N8N_LINKEDIN_WEBHOOK_SECRET = os.environ.get("N8N_LINKEDIN_WEBHOOK_SECRET", "").strip()
N8N_LINKEDIN_TARGET = os.environ.get("N8N_LINKEDIN_TARGET", "PERSON").strip().upper()
# Kept for existing installations using the original generic webhook mode.
LINKEDIN_PUBLISH_WEBHOOK_URL = os.environ.get("LINKEDIN_PUBLISH_WEBHOOK_URL", "").strip()
LINKEDIN_PUBLISH_WEBHOOK_SECRET = os.environ.get("LINKEDIN_PUBLISH_WEBHOOK_SECRET", "").strip()
LINKEDIN_HTTP_TIMEOUT_SECONDS = int(os.environ.get("LINKEDIN_HTTP_TIMEOUT_SECONDS", "60"))
LINKEDIN_GENERATE_IMAGES = os.environ.get("LINKEDIN_GENERATE_IMAGES", "False").lower() in ("true", "1", "yes")
LINKEDIN_IMAGE_PROVIDER = os.environ.get("LINKEDIN_IMAGE_PROVIDER", "cloudflare").strip().lower()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
GEMINI_IMAGE_MODEL = os.environ.get("GEMINI_IMAGE_MODEL", "gemini-3.1-flash-image").strip()
GEMINI_IMAGE_SIZE = os.environ.get("GEMINI_IMAGE_SIZE", "1K").strip().upper()
CLOUDFLARE_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID", "").strip()
CLOUDFLARE_API_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN", "").strip()
CLOUDFLARE_IMAGE_MODEL = os.environ.get(
    "CLOUDFLARE_IMAGE_MODEL",
    "@cf/black-forest-labs/flux-2-dev",
).strip()
CLOUDFLARE_IMAGE_STEPS = int(os.environ.get("CLOUDFLARE_IMAGE_STEPS", "4"))
CLOUDFLARE_IMAGE_WIDTH = int(os.environ.get("CLOUDFLARE_IMAGE_WIDTH", "1024"))
CLOUDFLARE_IMAGE_HEIGHT = int(os.environ.get("CLOUDFLARE_IMAGE_HEIGHT", "1280"))
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_IMAGE_MODEL = os.environ.get("OPENAI_IMAGE_MODEL", "gpt-image-1.5").strip()
OPENAI_IMAGE_QUALITY = os.environ.get("OPENAI_IMAGE_QUALITY", "high").strip().lower()
PUBLIC_BACKEND_URL = os.environ.get("PUBLIC_BACKEND_URL", "http://localhost:8000").strip().rstrip("/")
UPLOAD_POST_API_BASE_URL = os.environ.get(
    "UPLOAD_POST_API_BASE_URL",
    "https://api.upload-post.com/api",
).strip().rstrip("/")
UPLOAD_POST_API_KEY = os.environ.get("UPLOAD_POST_API_KEY", "").strip()
UPLOAD_POST_WEBHOOK_SECRET = os.environ.get("UPLOAD_POST_WEBHOOK_SECRET", "").strip()
UPLOAD_POST_CONNECTION_RETURN_URL = os.environ.get(
    "UPLOAD_POST_CONNECTION_RETURN_URL",
    "",
).strip()
UPLOAD_POST_HTTP_TIMEOUT_SECONDS = _bounded_env_int("UPLOAD_POST_HTTP_TIMEOUT_SECONDS", 30, 1, 60)
ZERNIO_API_BASE_URL = os.environ.get(
    "ZERNIO_API_BASE_URL",
    "https://zernio.com/api",
).strip().rstrip("/")
ZERNIO_API_KEY = os.environ.get("ZERNIO_API_KEY", "").strip()
ZERNIO_WEBHOOK_SECRET = os.environ.get("ZERNIO_WEBHOOK_SECRET", "").strip()
ZERNIO_CONNECTION_RETURN_URL = os.environ.get(
    "ZERNIO_CONNECTION_RETURN_URL",
    "",
).strip()
ZERNIO_HTTP_TIMEOUT_SECONDS = _bounded_env_int("ZERNIO_HTTP_TIMEOUT_SECONDS", 30, 1, 60)
SOCIAL_PUBLISH_MAX_ATTEMPTS = _bounded_env_int("SOCIAL_PUBLISH_MAX_ATTEMPTS", 3, 1, 5)
SOCIAL_PUBLISH_RETRY_BASE_SECONDS = _bounded_env_int("SOCIAL_PUBLISH_RETRY_BASE_SECONDS", 60, 1, 3600)
SOCIAL_PUBLISH_RETRY_MAX_SECONDS = _bounded_env_int("SOCIAL_PUBLISH_RETRY_MAX_SECONDS", 900, 1, 86400)
if SOCIAL_PUBLISH_RETRY_MAX_SECONDS < SOCIAL_PUBLISH_RETRY_BASE_SECONDS:
    raise ValueError("SOCIAL_PUBLISH_RETRY_MAX_SECONDS must be at least SOCIAL_PUBLISH_RETRY_BASE_SECONDS.")
SOCIAL_PUBLISH_CLAIM_TTL_SECONDS = _bounded_env_int("SOCIAL_PUBLISH_CLAIM_TTL_SECONDS", 300, 30, 3600)
SOCIAL_HEALTH_OVERDUE_JOB_MINUTES = _bounded_env_int("SOCIAL_HEALTH_OVERDUE_JOB_MINUTES", 10, 1, 1440)
SOCIAL_HEALTH_FAILED_JOB_THRESHOLD = _bounded_env_int("SOCIAL_HEALTH_FAILED_JOB_THRESHOLD", 5, 1, 10000)
LINKEDIN_LEGACY_CALLBACK_REQUIRE_TIMESTAMP = _env_bool(
    "LINKEDIN_LEGACY_CALLBACK_REQUIRE_TIMESTAMP",
    not DEBUG,
)
LINKEDIN_LEGACY_CALLBACK_MAX_AGE_SECONDS = _bounded_env_int(
    "LINKEDIN_LEGACY_CALLBACK_MAX_AGE_SECONDS",
    300,
    30,
    3600,
)
CONTENT_STUDIO_DRAFT_ONLY_ALLOWED = os.environ.get(
    "CONTENT_STUDIO_DRAFT_ONLY_ALLOWED", "true"
).strip().lower() in {"true", "1", "yes"}
SOCIAL_QUALITY_LLM_ENABLED = os.environ.get(
    "SOCIAL_QUALITY_LLM_ENABLED", "false" if "test" in sys.argv else "true"
).strip().lower() in {"true", "1", "yes"}

# ── Remote Celery Worker Keep-Alive & Wake Configuration ─────────────────────
WORKER_1_URL = os.environ.get("WORKER_1_URL", "http://127.0.0.1:10000").rstrip("/")
WORKER_2_URL = os.environ.get("WORKER_2_URL", "http://127.0.0.1:10001").rstrip("/")
WORKER_WAKE_TOKEN = os.environ.get("WORKER_WAKE_TOKEN", "").strip()
WORKER_NAME = os.environ.get("WORKER_NAME", "").strip()




