import { Check, Download, Image as ImageIcon, LoaderCircle, Save, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { contentStudioApi } from '../../../api/contentStudio'
import { KnowledgeHubLinks } from '../KnowledgeHubLinks'
import { BrandBrainPanel } from '../knowledge/BrandBrainPanel'
import { ContentSourcesPanel } from '../knowledge/ContentSourcesPanel'
import { StoryInterviewPanel } from '../knowledge/StoryInterviewPanel'
import { useContentStudio } from '../ContentStudioContext'

const dayNames = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
const splitList = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean)

export function ContentSettingsView() {
  const { settingsDraft, setSettingsDraft, saveSettings, busy, isDemo, reload } = useContentStudio()
  const [dataBusy, setDataBusy] = useState<'export' | 'delete' | ''>('')
  const [confirmation, setConfirmation] = useState('')
  const [dataMessage, setDataMessage] = useState('')
  const [dataError, setDataError] = useState(false)
  const [searchParams] = useSearchParams()
  const requestedPanel = searchParams.get('panel')
  const panel = requestedPanel === 'brand' || requestedPanel === 'sources' || requestedPanel === 'story' ? requestedPanel : null
  return <section className="li-settings-page" aria-label="Content Studio settings">
    {!panel && <div className="li-settings-actions"><button className="button button-dark" onClick={() => void saveSettings()} disabled={busy === 'settings'} aria-busy={busy === "settings"}>{busy === 'settings' ? <LoaderCircle className="spin" size={16} /> : <Save size={16} />} Save changes</button></div>}
    <KnowledgeHubLinks base="/content/settings" />
    {panel === 'brand' && <BrandBrainPanel />}
    {panel === 'sources' && <ContentSourcesPanel />}
    {panel === 'story' && <StoryInterviewPanel />}
    {!panel && <>
    <div className="li-settings-grid">
      <div className="card li-settings-card"><div className="li-card-title"><span>1</span><div><h3>Business profile</h3><p>Tell the writer who it represents.</p></div></div><div className="li-form-grid"><label className="li-field"><span>Business name</span><input value={settingsDraft.page_name} onChange={(e) => setSettingsDraft({ ...settingsDraft, page_name: e.target.value })} placeholder="Your company" /></label><label className="li-field"><span>Language</span><select value={settingsDraft.language} onChange={(e) => setSettingsDraft({ ...settingsDraft, language: e.target.value })}><option>English</option><option>Hindi</option><option>Spanish</option><option>French</option></select></label><label className="li-field full"><span>What does the business do?</span><textarea value={settingsDraft.company_description} onChange={(e) => setSettingsDraft({ ...settingsDraft, company_description: e.target.value })} placeholder="Products, services, positioning, and anything the writer should know." /></label><label className="li-field full"><span>Target audience</span><textarea value={settingsDraft.audience} onChange={(e) => setSettingsDraft({ ...settingsDraft, audience: e.target.value })} placeholder="Who should find these posts useful?" /></label></div></div>

      <div className="card li-settings-card"><div className="li-card-title"><span>2</span><div><h3>Content style</h3><p>Control the voice and visual quality.</p></div></div><div className="li-form-grid"><label className="li-field"><span>Brand voice</span><input value={settingsDraft.brand_voice} onChange={(e) => setSettingsDraft({ ...settingsDraft, brand_voice: e.target.value })} /></label><label className="li-field"><span>Content pillars <small>comma separated</small></span><input value={settingsDraft.content_pillars.join(', ')} onChange={(e) => setSettingsDraft({ ...settingsDraft, content_pillars: splitList(e.target.value) })} /></label><label className="li-field full"><span>Visual direction</span><textarea value={settingsDraft.image_style} onChange={(e) => setSettingsDraft({ ...settingsDraft, image_style: e.target.value })} placeholder="Example: editorial photography, navy and orange palette, simple compositions" /></label><div className={`provider-state image-provider ${settingsDraft.image_provider_ready.ready ? 'ready' : ''}`}><span>{settingsDraft.image_provider_ready.ready ? <Check size={16} /> : <ImageIcon size={16} />}</span><div><strong>{settingsDraft.image_provider_ready.ready ? 'Image creation ready' : 'Image creation needs attention'}</strong><small>{settingsDraft.image_provider_ready.ready ? 'Images can be created for new posts.' : 'Ask a workspace administrator to finish image setup.'}</small></div></div><label className="li-field"><span>Calls to action</span><input value={settingsDraft.calls_to_action.join(', ')} onChange={(e) => setSettingsDraft({ ...settingsDraft, calls_to_action: splitList(e.target.value) })} /></label><label className="li-field"><span>Topics to avoid</span><input value={settingsDraft.forbidden_topics.join(', ')} onChange={(e) => setSettingsDraft({ ...settingsDraft, forbidden_topics: splitList(e.target.value) })} /></label></div></div>

      <div className="card li-settings-card"><div className="li-card-title"><span>3</span><div><h3>Schedule</h3><p>Choose when approved posts publish.</p></div></div><div className="li-days">{dayNames.map((day, index) => <button type="button" aria-pressed={settingsDraft.schedule_days.includes(index)} key={day} className={settingsDraft.schedule_days.includes(index) ? 'selected' : ''} onClick={() => setSettingsDraft({ ...settingsDraft, schedule_days: settingsDraft.schedule_days.includes(index) ? settingsDraft.schedule_days.filter((value) => value !== index) : [...settingsDraft.schedule_days, index].sort() })}><strong>{day.slice(0, 3)}</strong></button>)}</div><div className="li-form-grid compact"><label className="li-field"><span>Publishing time</span><input type="time" value={settingsDraft.post_time.slice(0, 5)} onChange={(e) => setSettingsDraft({ ...settingsDraft, post_time: e.target.value })} /></label><label className="li-field"><span>Timezone</span><select value={settingsDraft.timezone} onChange={(e) => setSettingsDraft({ ...settingsDraft, timezone: e.target.value })}><option>Asia/Kolkata</option><option>Europe/London</option><option>America/New_York</option><option>UTC</option></select></label></div></div>

      <div className="card li-settings-card"><div className="li-card-title"><span>4</span><div><h3>Approvals</h3><p>Choose how posts enter the calendar.</p></div></div><fieldset className="li-choice-group"><legend>Approval</legend><label><input type="radio" checked={settingsDraft.approval_mode === 'REQUIRE_APPROVAL'} onChange={() => setSettingsDraft({ ...settingsDraft, approval_mode: 'REQUIRE_APPROVAL' })} /><span><strong>Review every post</strong><small>Recommended while refining the content style.</small></span></label><label><input type="radio" checked={settingsDraft.approval_mode === 'AUTO_PUBLISH'} onChange={() => setSettingsDraft({ ...settingsDraft, approval_mode: 'AUTO_PUBLISH' })} /><span><strong>Approve automatically</strong><small>Created posts enter the schedule immediately.</small></span></label></fieldset></div>
    </div>

    <details className="card content-advanced"><summary>Advanced</summary><div><p>Fine-tune how far ahead Content Studio prepares posts.</p><div className="li-form-grid compact"><label className="li-field"><span>Posts each week</span><input type="number" min="1" max="14" value={settingsDraft.posts_per_week} onChange={(e) => setSettingsDraft({ ...settingsDraft, posts_per_week: Number(e.target.value) })} /></label><label className="li-field"><span>Plan ahead <small>days</small></span><input type="number" min="1" max="90" value={settingsDraft.queue_horizon_days} onChange={(e) => setSettingsDraft({ ...settingsDraft, queue_horizon_days: Number(e.target.value) })} /></label></div>
      <section className="content-data-controls" aria-labelledby="content-data-title"><h3 id="content-data-title">Your Content Studio data</h3><p>Download a copy, or permanently remove posts, sources, connections, and settings from this workspace.</p><div className="content-data-actions"><button type="button" className="li-quiet-button" disabled={Boolean(dataBusy) || isDemo} aria-busy={dataBusy === "export"} onClick={async () => { setDataBusy('export'); setDataMessage(''); setDataError(false); try { const payload = await contentStudioApi.exportData(); const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'content-studio-export.json'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); setDataMessage('Your download is ready.') } catch (error) { setDataError(true); setDataMessage(error instanceof Error ? error.message : 'Could not export Content Studio data.') } finally { setDataBusy('') } }}>{dataBusy === 'export' ? <LoaderCircle className="spin" size={16} /> : <Download size={16} />} Download data</button></div>
      <div className="content-delete-control"><label className="li-field"><span>To delete, type DELETE CONTENT STUDIO</span><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" /></label><button type="button" className="content-danger-button" disabled={Boolean(dataBusy) || confirmation !== 'DELETE CONTENT STUDIO' || isDemo} aria-busy={dataBusy === "delete"} onClick={async () => { setDataBusy('delete'); setDataMessage(''); setDataError(false); try { await contentStudioApi.deleteData(confirmation); setConfirmation(''); setDataMessage('Content Studio data was deleted from this workspace.'); await reload() } catch (error) { setDataError(true); setDataMessage(error instanceof Error ? error.message : 'Could not delete Content Studio data.') } finally { setDataBusy('') } }}>{dataBusy === 'delete' ? <LoaderCircle className="spin" size={16} /> : <Trash2 size={16} />} Delete Content Studio data</button></div>
      {isDemo && <p>Data actions are unavailable in demo mode.</p>}{dataMessage && <p className={dataError ? 'content-data-message error' : 'content-data-message'} role={dataError ? 'alert' : 'status'}>{dataMessage}</p>}</section>
    </div></details>
    </>}
  </section>
}
