from django.urls import path

from integrations.social.views import (
    BrandBrainAPIView,
    BrandVoiceSuggestionAPIView,
    SocialAnalyticsAPIView,
    SocialAnalyticsRefreshAPIView,
    SocialAnalyticsSuggestionAPIView,
    ContentStudioConnectionCancelAPIView,
    ContentStudioConnectionCompleteAPIView,
    ContentStudioConnectionChoicesAPIView,
    ContentStudioConnectionSelectAPIView,
    ContentStudioConnectionStartAPIView,
    ContentStudioOnboardingAPIView,
    ContentStudioOnboardingStepAPIView,
    ContentStudioAssistantAPIView,
    ContentStudioBusinessProfileAPIView,
    ContentStudioHomeAPIView,
    ContentStudioDataDeletionAPIView,
    ContentStudioDataExportAPIView,
    SocialComposerOptionsAPIView,
    SocialMediaAssetDetailAPIView,
    SocialMediaAssetListCreateAPIView,
    SocialMediaRegenerateAPIView,
    SocialMediaReorderAPIView,
    SocialPublicMediaAPIView,
    SocialVariantApproveAPIView,
    SocialPostDetailAPIView,
    SocialPostGenerateAPIView,
    SocialPostSeriesAPIView,
    SocialPostListCreateAPIView,
    SocialPostSubmitReviewAPIView,
    SocialPostScheduleAPIView,
    SocialVariantDetailAPIView,
    SocialVariantRewriteAPIView,
    SocialApprovalsAPIView,
    SocialApprovalActionAPIView,
    SocialPublishNowAPIView,
    SocialBatchApprovalAPIView,
    SocialCalendarAPIView,
    SocialConnectionActionAPIView,
    SocialConnectionsAPIView,
    ContentSourcesAPIView,
    SocialLibraryAPIView,
    SocialLibraryActionAPIView,
    SocialRescheduleAPIView,
    StoryInterviewAPIView,
)
from integrations.social.engagement_views import (
    EngagementAutomationDetailAPIView,
    EngagementAutomationsAPIView,
    EngagementCampaignDetailAPIView,
    EngagementCampaignsAPIView,
    EngagementOverviewAPIView,
    EngagementReviewDetailAPIView,
    EngagementTestTriggerAPIView,
)


urlpatterns = [
    path("media/<uuid:asset_id>/", SocialPublicMediaAPIView.as_view(), name="social-media-public"),
    path("brand-brain/", BrandBrainAPIView.as_view(), name="social-brand-brain"),
    path("brand-brain/suggestions/<uuid:suggestion_id>/", BrandVoiceSuggestionAPIView.as_view(), name="social-brand-voice-suggestion"),
    path("sources/", ContentSourcesAPIView.as_view(), name="social-content-sources"),
    path("story-interview/", StoryInterviewAPIView.as_view(), name="social-story-interview"),
    path("studio/home/", ContentStudioHomeAPIView.as_view(), name="social-studio-home"),
    path("assistant/chat/", ContentStudioAssistantAPIView.as_view(), name="social-assistant-chat"),
    path("studio/data-export/", ContentStudioDataExportAPIView.as_view(), name="social-data-export"),
    path("studio/data/", ContentStudioDataDeletionAPIView.as_view(), name="social-data-delete"),
    path("analytics/", SocialAnalyticsAPIView.as_view(), name="social-analytics"),
    path("analytics/refresh/", SocialAnalyticsRefreshAPIView.as_view(), name="social-analytics-refresh"),
    path("analytics/suggestions/<uuid:suggestion_id>/", SocialAnalyticsSuggestionAPIView.as_view(), name="social-analytics-suggestion"),
    path("approvals/", SocialApprovalsAPIView.as_view(), name="social-approvals"),
    path("approvals/batch/", SocialBatchApprovalAPIView.as_view(), name="social-approvals-batch"),
    path("variants/<uuid:variant_id>/review/", SocialApprovalActionAPIView.as_view(), name="social-approval-action"),
    path("variants/<uuid:variant_id>/publish-now/", SocialPublishNowAPIView.as_view(), name="social-publish-now"),
    path("calendar/", SocialCalendarAPIView.as_view(), name="social-calendar"),
    path("variants/<uuid:variant_id>/reschedule/", SocialRescheduleAPIView.as_view(), name="social-reschedule"),
    path("library/", SocialLibraryAPIView.as_view(), name="social-library"),
    path("posts/<uuid:post_id>/library-action/", SocialLibraryActionAPIView.as_view(), name="social-library-action"),
    path("connections/", SocialConnectionsAPIView.as_view(), name="social-connections"),
    path("connections/<uuid:connection_id>/action/", SocialConnectionActionAPIView.as_view(), name="social-connection-action"),
    path("engagement/", EngagementOverviewAPIView.as_view(), name="social-engagement-overview"),
    path("engagement/reviews/<uuid:review_id>/", EngagementReviewDetailAPIView.as_view(), name="social-engagement-review"),
    path("engagement/automations/", EngagementAutomationsAPIView.as_view(), name="social-engagement-automations"),
    path("engagement/automations/<uuid:automation_id>/", EngagementAutomationDetailAPIView.as_view(), name="social-engagement-automation"),
    path("engagement/test-trigger/", EngagementTestTriggerAPIView.as_view(), name="social-engagement-test-trigger"),
    path("engagement/campaigns/", EngagementCampaignsAPIView.as_view(), name="social-engagement-campaigns"),
    path("engagement/campaigns/<uuid:campaign_id>/", EngagementCampaignDetailAPIView.as_view(), name="social-engagement-campaign"),
    path("composer/options/", SocialComposerOptionsAPIView.as_view(), name="social-composer-options"),
    path("posts/", SocialPostListCreateAPIView.as_view(), name="social-post-list"),
    path("posts/generate/", SocialPostGenerateAPIView.as_view(), name="social-post-generate"),
    path("posts/series/", SocialPostSeriesAPIView.as_view(), name="social-post-series"),
    path("posts/<uuid:post_id>/", SocialPostDetailAPIView.as_view(), name="social-post-detail"),
    path("posts/<uuid:post_id>/submit-review/", SocialPostSubmitReviewAPIView.as_view(), name="social-post-submit-review"),
    path("posts/<uuid:post_id>/schedule/", SocialPostScheduleAPIView.as_view(), name="social-post-schedule"),
    path("variants/<uuid:variant_id>/", SocialVariantDetailAPIView.as_view(), name="social-variant-detail"),
    path("variants/<uuid:variant_id>/rewrite/", SocialVariantRewriteAPIView.as_view(), name="social-variant-rewrite"),
    path("onboarding/", ContentStudioOnboardingAPIView.as_view(), name="content-studio-onboarding"),
    path("onboarding/steps/<int:step>/", ContentStudioOnboardingStepAPIView.as_view(), name="content-studio-onboarding-step"),
    path("onboarding/business/", ContentStudioBusinessProfileAPIView.as_view(), name="content-studio-business-profile"),
    path("onboarding/connection/start/", ContentStudioConnectionStartAPIView.as_view(), name="content-studio-connection-start"),
    path("onboarding/connection/choices/", ContentStudioConnectionChoicesAPIView.as_view(), name="content-studio-connection-choices"),
    path("onboarding/connection/select/", ContentStudioConnectionSelectAPIView.as_view(), name="content-studio-connection-select"),
    path("onboarding/connection/complete/", ContentStudioConnectionCompleteAPIView.as_view(), name="content-studio-connection-complete"),
    path("onboarding/connection/cancel/", ContentStudioConnectionCancelAPIView.as_view(), name="content-studio-connection-cancel"),
    path(
        "variants/<uuid:variant_id>/media/",
        SocialMediaAssetListCreateAPIView.as_view(),
        name="social-media-list",
    ),
    path(
        "variants/<uuid:variant_id>/media/<uuid:pk>/",
        SocialMediaAssetDetailAPIView.as_view(),
        name="social-media-detail",
    ),
    path(
        "variants/<uuid:variant_id>/media/reorder/",
        SocialMediaReorderAPIView.as_view(),
        name="social-media-reorder",
    ),
    path(
        "variants/<uuid:variant_id>/media/regenerate-image/",
        SocialMediaRegenerateAPIView.as_view(),
        name="social-media-regenerate",
    ),
    path(
        "variants/<uuid:variant_id>/approve/",
        SocialVariantApproveAPIView.as_view(),
        name="social-variant-approve",
    ),
]
