from enum import Enum

class LLMOperation(str, Enum):
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    EXTRACT = "EXTRACT"
    CLASSIFY = "CLASSIFY"
    GENERATE = "GENERATE"
    SUMMARIZE = "SUMMARIZE"

class LLMComplexity(str, Enum):
    SIMPLE = "SIMPLE"
    STANDARD = "STANDARD"
    COMPLEX = "COMPLEX"

class LLMCapability(str, Enum):
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    REASONING = "REASONING"
    EXTRACTION = "EXTRACTION"
    CLASSIFICATION = "CLASSIFICATION"
    GENERATION = "GENERATION"
    SUMMARIZATION = "SUMMARIZATION"

class LLMErrorCategory(str, Enum):
    RATE_LIMITED = "RATE_LIMITED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    TEMPORARY_PROVIDER_ERROR = "TEMPORARY_PROVIDER_ERROR"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    TIMEOUT = "TIMEOUT"
    INVALID_REQUEST = "INVALID_REQUEST"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    UNKNOWN = "UNKNOWN"
