import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("prospecting", "0019_workspacemembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("MANUAL", "Manual"), ("BUFFER", "Buffer (legacy)"), ("N8N", "n8n (legacy)"), ("WEBHOOK", "Webhook (legacy)"), ("UPLOAD_POST", "Upload Post"), ("ZERNIO", "Zernio")], max_length=20)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("external_id", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("CLAIMED", "Claimed"), ("SUBMITTED", "Submitted"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], db_index=True, default="PENDING", max_length=20)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_type", models.CharField(choices=[("TEXT", "Text"), ("URL", "URL"), ("DOCUMENT", "Document"), ("TRANSCRIPT", "Transcript"), ("VOICE_NOTE", "Voice note")], default="TEXT", max_length=20)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("text_content", models.TextField(blank=True, default="")),
                ("source_url", models.URLField(blank=True, default="", max_length=2000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_reusable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("legacy_linkedin_brief_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_content_sources", to="prospecting.workspace")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SocialConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("network", models.CharField(choices=[("LINKEDIN", "LinkedIn"), ("X", "X"), ("INSTAGRAM", "Instagram")], max_length=20)),
                ("provider", models.CharField(choices=[("MANUAL", "Manual"), ("BUFFER", "Buffer (legacy)"), ("N8N", "n8n (legacy)"), ("WEBHOOK", "Webhook (legacy)"), ("UPLOAD_POST", "Upload Post"), ("ZERNIO", "Zernio")], max_length=20)),
                ("provider_profile_id", models.CharField(blank=True, default="", max_length=500)),
                ("provider_account_id", models.CharField(blank=True, default="", max_length=500)),
                ("display_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(choices=[("PERSON", "Person"), ("ORGANIZATION", "Organization"), ("CREATOR", "Creator"), ("BUSINESS", "Business")], default="ORGANIZATION", max_length=20)),
                ("status", models.CharField(choices=[("DISCONNECTED", "Disconnected"), ("CONNECTING", "Connecting"), ("CONNECTED", "Connected"), ("ERROR", "Error"), ("REVOKED", "Revoked")], db_index=True, default="DISCONNECTED", max_length=20)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("legacy_linkedin_settings_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_connections", to="prospecting.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("MANUAL", "Manual"), ("BUFFER", "Buffer (legacy)"), ("N8N", "n8n (legacy)"), ("WEBHOOK", "Webhook (legacy)"), ("UPLOAD_POST", "Upload Post"), ("ZERNIO", "Zernio")], max_length=20)),
                ("external_event_id", models.CharField(blank=True, default="", max_length=500)),
                ("event_type", models.CharField(max_length=100)),
                ("normalized_status", models.CharField(blank=True, choices=[("PENDING", "Pending"), ("CLAIMED", "Claimed"), ("SUBMITTED", "Submitted"), ("SUCCEEDED", "Succeeded"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], max_length=20, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_provider_events", to="prospecting.workspace")),
                ("publish_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="social_content.publishjob")),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="social_content.socialconnection")),
            ],
            options={"ordering": ["-received_at"]},
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idea_title", models.CharField(max_length=255)),
                ("idea_text", models.TextField(blank=True, default="")),
                ("state", models.CharField(choices=[("DRAFT", "Draft"), ("SCHEDULED", "Scheduled"), ("READY", "Ready"), ("PUBLISHING", "Publishing"), ("SUBMITTED", "Submitted"), ("PUBLISHED", "Published"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("legacy_linkedin_post_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posts", to="social_content.contentsource")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_posts", to="prospecting.workspace")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("asset_type", models.CharField(choices=[("IMAGE", "Image"), ("MULTI_IMAGE", "Multiple images"), ("VIDEO", "Video"), ("DOCUMENT", "Document")], max_length=20)),
                ("storage_url", models.URLField(max_length=2000)),
                ("alt_text", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("legacy_linkedin_post_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="social_media_assets", to="prospecting.workspace")),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="social_content.socialpost")),
            ],
            options={"ordering": ["sort_order", "created_at"]},
        ),
        migrations.CreateModel(
            name="SocialPostVariant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("network", models.CharField(choices=[("LINKEDIN", "LinkedIn"), ("X", "X"), ("INSTAGRAM", "Instagram")], max_length=20)),
                ("copy", models.TextField()),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SCHEDULED", "Scheduled"), ("READY", "Ready"), ("PUBLISHING", "Publishing"), ("SUBMITTED", "Submitted"), ("PUBLISHED", "Published"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=20)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("connection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="variants", to="social_content.socialconnection")),
                ("post", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="social_content.socialpost")),
            ],
            options={"ordering": ["scheduled_for", "created_at"]},
        ),
        migrations.AddField(
            model_name="publishjob",
            name="variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publish_jobs", to="social_content.socialpostvariant"),
        ),
        migrations.CreateModel(
            name="SocialPostVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("copy", models.TextField()),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("media_snapshot", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_social_post_versions", to=settings.AUTH_USER_MODEL)),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="social_content.socialpostvariant")),
            ],
            options={"ordering": ["version"]},
        ),
        migrations.AddField(
            model_name="publishjob",
            name="approved_version",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="publish_jobs", to="social_content.socialpostversion"),
        ),
        migrations.CreateModel(
            name="SocialWorkspaceSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("brand_name", models.CharField(default="Your business", max_length=255)),
                ("language", models.CharField(default="English", max_length=50)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("approval_mode", models.CharField(choices=[("REQUIRE_APPROVAL", "Require approval"), ("AUTO_PUBLISH", "Publish automatically")], default="REQUIRE_APPROVAL", max_length=30)),
                ("schedule_days", models.JSONField(blank=True, default=list)),
                ("post_time", models.TimeField(default=datetime.time(10, 0))),
                ("posts_per_week", models.PositiveSmallIntegerField(default=5)),
                ("queue_horizon_days", models.PositiveSmallIntegerField(default=14)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("legacy_linkedin_settings_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="social_content_settings", to="prospecting.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="BrandProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("audience", models.TextField(blank=True, default="")),
                ("voice", models.CharField(default="Clear, credible and human", max_length=255)),
                ("content_pillars", models.JSONField(blank=True, default=list)),
                ("calls_to_action", models.JSONField(blank=True, default=list)),
                ("visual_direction", models.TextField(blank=True, default="")),
                ("forbidden_topics", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("settings", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="brand_profile", to="social_content.socialworkspacesettings")),
            ],
        ),
        migrations.AddIndex(model_name="contentsource", index=models.Index(fields=["workspace", "source_type", "is_active"], name="social_src_workspace_type_idx")),
        migrations.AddIndex(model_name="socialconnection", index=models.Index(fields=["workspace", "network", "status"], name="social_conn_workspace_idx")),
        migrations.AddConstraint(model_name="socialconnection", constraint=models.UniqueConstraint(condition=models.Q(("provider_account_id", ""), _negated=True), fields=("workspace", "network", "provider", "provider_account_id"), name="unique_social_provider_account")),
        migrations.AddIndex(model_name="providerevent", index=models.Index(fields=["workspace", "provider", "received_at"], name="social_event_workspace_idx")),
        migrations.AddIndex(model_name="socialpost", index=models.Index(fields=["workspace", "state", "created_at"], name="social_post_workspace_idx")),
        migrations.AddIndex(model_name="mediaasset", index=models.Index(fields=["workspace", "asset_type"], name="social_asset_workspace_idx")),
        migrations.AddIndex(model_name="socialpostvariant", index=models.Index(fields=["network", "status", "scheduled_for"], name="social_variant_due_idx")),
        migrations.AddConstraint(model_name="socialpostvariant", constraint=models.UniqueConstraint(fields=("post", "network"), name="unique_social_post_network")),
        migrations.AddConstraint(model_name="socialpostversion", constraint=models.UniqueConstraint(fields=("variant", "version"), name="unique_social_variant_version")),
        migrations.AddIndex(model_name="publishjob", index=models.Index(fields=["provider", "status", "created_at"], name="social_job_provider_idx")),
    ]
