# Generated by Django 6.0.6 on 2026-09-18 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0019_workspacemembership'),
        ('social_content', '0012_route_all_workspaces_to_zernio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(max_length=500, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('account_id', models.CharField(blank=True, default='', max_length=500)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('X', 'X'), ('INSTAGRAM', 'Instagram')], db_index=True, max_length=20)),
                ('provider_contact_id', models.CharField(max_length=500)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_contacts', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('COMMENT_REPLY', 'Comment reply'), ('DIRECT_MESSAGE', 'Direct message'), ('STORY_REPLY', 'Story reply')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Needs review'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DISMISSED', 'Dismissed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('source_label', models.CharField(blank=True, default='', max_length=255)),
                ('incoming_text', models.TextField(blank=True, default='')),
                ('suggested_text', models.TextField(blank=True, default='')),
                ('final_text', models.TextField(blank=True, default='')),
                ('conversation_id', models.CharField(blank=True, default='', max_length=500)),
                ('provider_post_id', models.CharField(blank=True, default='', max_length=500)),
                ('provider_comment_id', models.CharField(blank=True, default='', max_length=500)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_engagement_reviews', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_engagement_reviews', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_review_items', to='social_content.socialconnection')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='social_content.engagementcontact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_review_items', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('COMMENT_TO_DM', 'Comment to DM'), ('STORY_REPLY', 'Story reply'), ('DM_KEYWORD', 'DM keyword'), ('CLICK_TO_DM', 'Click-to-DM')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Needs approval'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('match_mode', models.CharField(default='contains', max_length=20)),
                ('approved_dm_message', models.TextField(blank=True, default='')),
                ('approved_comment_reply', models.TextField(blank=True, default='')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('provider_automation_id', models.CharField(blank=True, default='', max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_engagement_automations', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_automations', to='social_content.socialconnection')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_engagement_automations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_automations', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='engage_auto_workspace_idx')],
            },
        ),
        migrations.CreateModel(
            name='EngagementCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Needs approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('provider_sequence_id', models.CharField(blank=True, default='', max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_engagement_campaigns', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_campaigns', to='social_content.socialconnection')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_engagement_campaigns', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_campaigns', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='engage_campaign_ws_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='engagementcontact',
            constraint=models.UniqueConstraint(fields=('workspace', 'platform', 'provider_contact_id'), name='unique_workspace_engagement_contact'),
        ),
        migrations.AddIndex(
            model_name='engagementreviewitem',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='engage_review_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagementreviewitem',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider_event_id',), name='unique_engagement_provider_event'),
        ),
    ]
