# Generated by Django 6.0.6 on 2026-09-24 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0019_workspacemembership'),
        ('social_content', '0014_billing_and_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='billing_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('ADVANCE', 'Advance'), ('ADMIN', 'Admin')], db_index=True, default='FREE', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('expected_operations', models.PositiveIntegerField(default=1)),
                ('completed_operations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('REFUNDED', 'Refunded')], db_index=True, default='RESERVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_reservations', to='social_content.socialpost')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_reservations', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='social_content.creditreservation'),
        ),
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='social_content.billinginvoice')),
            ],
            options={
                'ordering': ['-processed_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_billing_provider_event')],
            },
        ),
        migrations.AddIndex(
            model_name='creditreservation',
            index=models.Index(fields=['workspace', 'status'], name='credit_reservation_ws_idx'),
        ),
    ]
