# Generated by Django 6.0.6 on 2026-08-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrun',
            name='cost_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
