# Generated by Django 6.0.6 on 2026-08-19 16:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_promptrun_cost_usd_promptrun_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='error_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='input_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='output_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='prompt_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='prompt_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='provider_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='rendered_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='span_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='status',
            field=models.CharField(default='success', max_length=50),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='promptrun',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='LLMPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=150)),
                ('version', models.IntegerField(default=1)),
                ('template', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('key', 'version')},
            },
        ),
        migrations.AddField(
            model_name='promptrun',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm.llmprompt'),
        ),
    ]
