# Generated by Django 6.0.6 on 2026-08-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_promptrun_completed_at_promptrun_correlation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptrun',
            name='prompt',
        ),
    ]
