# Generated by Django 6.0.6 on 2026-08-10 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_leads_found', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_runs', to='knowledge_base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeadCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='prospecting.discoveryrun')),
            ],
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='website', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='prospecting.leadcompany')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_delivery', models.BooleanField(default=False)),
                ('has_scheduling', models.BooleanField(default=False)),
                ('needs_routing', models.BooleanField(default=False)),
                ('fleet_size_estimate', models.CharField(default='unknown', max_length=100)),
                ('lead_score', models.FloatField(default=0.0)),
                ('lead_score_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='prospecting.leadcompany')),
            ],
        ),
    ]
