# Generated by Django 6.0.6 on 2026-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcompany',
            name='website',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='linkedin',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='source',
            field=models.CharField(default='website', max_length=2000),
        ),
    ]
