# Generated by Django 6.0.6 on 2026-08-12 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0003_problemsignal_workspace_person_contactpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_reference', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='prospecting.leadcompany')),
            ],
            options={
                'unique_together': {('provider', 'external_id')},
            },
        ),
    ]
