# Generated by Django 6.0.6 on 2026-08-12 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('prospecting', '0004_companysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGuidance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('talking_points', models.JSONField(blank=True, default=list)),
                ('recommended_angle', models.CharField(max_length=255)),
                ('recommended_next_step', models.CharField(max_length=255)),
                ('message_draft', models.TextField()),
                ('risks', models.JSONField(blank=True, default=list)),
                ('unknowns', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_records', to='prospecting.prospectingcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_records', to='prospecting.leadcompany')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidance_records', to='prospecting.person')),
            ],
        ),
        migrations.CreateModel(
            name='TargetList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_smart', models.BooleanField(default=False)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_lists', to='knowledge_base.userprofile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_lists', to='prospecting.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('ENROLLED', 'Enrolled'), ('PAUSED', 'Paused'), ('EXCLUDED', 'Excluded'), ('COMPLETED', 'Completed')], default='ELIGIBLE', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='prospecting.prospectingcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_enrollments', to='prospecting.leadcompany')),
            ],
            options={
                'unique_together': {('campaign', 'company')},
            },
        ),
        migrations.CreateModel(
            name='ListMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='prospecting.leadcompany')),
                ('target_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='prospecting.targetlist')),
            ],
            options={
                'unique_together': {('target_list', 'company')},
            },
        ),
    ]
