# Generated by Django 6.0.6 on 2026-08-12 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0005_salesguidance_targetlist_campaignenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBounce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bounce_type', models.CharField(default='HARD', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='prospecting.prospectingcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='prospecting.leadcompany')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='prospecting.emailsequence')),
            ],
        ),
        migrations.CreateModel(
            name='InboundReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reply_text', models.TextField()),
                ('classification', models.CharField(choices=[('INTERESTED', 'Interested'), ('QUESTION', 'Question'), ('NOT_NOW', 'Not Now'), ('NOT_INTERESTED', 'Not Interested'), ('WRONG_PERSON', 'Wrong Person'), ('UNSUBSCRIBE', 'Unsubscribe'), ('OUT_OF_OFFICE', 'Out Of Office'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('confidence', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('requires_review', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='prospecting.emailmessage')),
            ],
        ),
    ]
