# Generated by Django 6.0.6 on 2026-08-13 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0006_emailbounce_emailunsubscribe_emailsequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('USEFUL', 'Useful'), ('WRONG_MATCH', 'Wrong Match'), ('BAD_EVIDENCE', 'Bad Evidence'), ('GOOD_EVIDENCE', 'Good Evidence'), ('GOOD_SIGNAL', 'Good Signal'), ('BAD_SIGNAL', 'Bad Signal'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='prospecting.leadcompany')),
            ],
        ),
    ]
