# Generated by Django 6.0.6 on 2026-08-13 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0007_leadfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMIntegrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_crm', models.CharField(default='MockCRM', max_length=100)),
                ('external_id', models.CharField(max_length=255)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_records', to='prospecting.leadcompany')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_records', to='prospecting.person')),
            ],
            options={
                'unique_together': {('external_crm', 'external_id')},
            },
        ),
    ]
