# Generated by Django 6.0.6 on 2026-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0008_crmintegrationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryrun',
            name='keyword',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='discoveryrun',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
