# Generated by Django 6.0.6 on 2026-08-16 18:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('prospecting', '0009_alter_discoveryrun_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcompany',
            name='discovery_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='prospecting.discoveryrun'),
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='knowledge_base.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='discovery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='prospecting.discovery'),
        ),
        migrations.CreateModel(
            name='ProspectingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_objective', models.TextField(blank=True, null=True)),
                ('raw_target', models.TextField(blank=True, null=True)),
                ('raw_qualification', models.TextField(blank=True, null=True)),
                ('clarification_history', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PARSING', 'Parsing'), ('NEEDS_CLARIFICATION', 'Needs Clarification'), ('READY_FOR_REVIEW', 'Ready For Review'), ('CONFIRMED', 'Confirmed'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospecting_requests', to='knowledge_base.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='discovery',
            name='prospecting_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='prospecting.prospectingrequest'),
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='prospecting_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to='prospecting.prospectingrequest'),
        ),
        migrations.CreateModel(
            name='ProspectingSpecificationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('schema_version', models.CharField(default='v1', max_length=50)),
                ('specification_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY_FOR_REVIEW', 'Ready For Review'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=50)),
                ('parser_model', models.CharField(blank=True, max_length=255, null=True)),
                ('parser_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_specifications', to='knowledge_base.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_versions', to='prospecting.prospectingrequest')),
            ],
            options={
                'unique_together': {('request', 'version')},
            },
        ),
        migrations.AddField(
            model_name='discovery',
            name='specification_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='prospecting.prospectingspecificationversion'),
        ),
        migrations.AddField(
            model_name='discoveryrun',
            name='specification_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_runs', to='prospecting.prospectingspecificationversion'),
        ),
        migrations.CreateModel(
            name='DiscoveryLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_leads', to='prospecting.leadcompany')),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_leads', to='prospecting.discoveryrun')),
            ],
            options={
                'unique_together': {('discovery_run', 'company')},
            },
        ),
    ]
