# Generated by Django 6.0.6 on 2026-08-18 17:24

import django.db.models.deletion
from django.db import migrations, models


def populate_campaigns(apps, schema_editor):
    Workspace = apps.get_model('prospecting', 'Workspace')
    ProspectingCampaign = apps.get_model('prospecting', 'ProspectingCampaign')
    DiscoveryRun = apps.get_model('prospecting', 'DiscoveryRun')
    DiscoveryLead = apps.get_model('prospecting', 'DiscoveryLead')

    workspace, _ = Workspace.objects.get_or_create(
        name='Default Workspace',
        defaults={'timezone': 'UTC'},
    )

    for run in DiscoveryRun.objects.select_related('prospecting_request').order_by('started_at'):
        request = run.prospecting_request
        campaign = run.campaign

        if campaign is None and request is not None:
            campaign = ProspectingCampaign.objects.filter(
                prospecting_request=request
            ).first()

        if campaign is None:
            keyword = ' '.join((run.keyword or '').split())
            campaign = ProspectingCampaign.objects.create(
                workspace=workspace,
                created_by=run.user_profile,
                prospecting_request=request,
                name=(keyword[:255] or 'Prospecting campaign'),
                description=(request.raw_target if request else '') or run.keyword,
                product_description=(request.raw_objective if request else '') or run.keyword,
                problem_statement=(request.raw_qualification if request else '') or run.keyword,
                geography={'location': run.location},
                status='ACTIVE',
            )
        elif request is not None and campaign.prospecting_request_id is None:
            request_already_linked = ProspectingCampaign.objects.filter(
                prospecting_request=request
            ).exclude(id=campaign.id).exists()
            if not request_already_linked:
                campaign.prospecting_request = request
                campaign.save(update_fields=['prospecting_request'])

        if run.campaign_id != campaign.id:
            run.campaign = campaign
            run.save(update_fields=['campaign'])

        companies = run.companies.all()
        companies.filter(campaign__isnull=True).update(campaign=campaign)
        for company_id in companies.values_list('id', flat=True):
            DiscoveryLead.objects.get_or_create(
                discovery_run=run,
                company_id=company_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0010_alter_leadcompany_discovery_run_discovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectingcampaign',
            name='prospecting_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to='prospecting.prospectingrequest'),
        ),
        migrations.RunPython(populate_campaigns, migrations.RunPython.noop),
    ]
