# Generated by Django 6.0.6 on 2026-08-22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0011_link_campaigns_to_searches'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLeadInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('company_summary', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('business_model', models.CharField(blank=True, default='', max_length=255)),
                ('services', models.JSONField(blank=True, default=list)),
                ('operational_profile', models.JSONField(blank=True, default=dict)),
                ('fit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fit_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('fit_reason', models.TextField(blank=True, default='')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('positive_factors', models.JSONField(blank=True, default=list)),
                ('negative_factors', models.JSONField(blank=True, default=list)),
                ('data_gaps', models.JSONField(blank=True, default=list)),
                ('recommended_next_step', models.TextField(blank=True, default='')),
                ('talking_points', models.JSONField(blank=True, default=list)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_insights', to='prospecting.prospectingcampaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_insights', to='prospecting.leadcompany')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', '-fit_score'], name='prospectin_campaig_5a8612_idx'), models.Index(fields=['company', 'campaign'], name='prospectin_company_889c82_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'campaign'), name='unique_company_campaign_insight')],
            },
        ),
    ]
