# Generated by Django 6.0.6 on 2026-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0013_leadcompany_enrichment_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignleadinsight',
            name='qualification_error',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignleadinsight',
            name='qualification_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='NOT_STARTED', max_length=50),
        ),
    ]
