# Generated by Django 6.0.6 on 2026-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0016_campaignleadinsight_sales_guidance_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverylead',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discoverylead',
            name='source_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
