# Generated by Django 6.0.6 on 2026-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0017_discoverylead_search_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRuntimeState',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Worker Runtime State',
                'verbose_name_plural': 'Worker Runtime State',
            },
        ),
    ]
