# Generated by Django 6.0.6 on 2026-08-29 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('prospecting', '0017_discoverylead_search_query_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_user_id', models.CharField(db_index=True, help_text='Meta Instagram-scoped user ID', max_length=100, unique=True)),
                ('facebook_page_id', models.CharField(blank=True, help_text='Connected Facebook Page ID', max_length=100, null=True)),
                ('username', models.CharField(db_index=True, help_text='Instagram handle/username', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Account display name', max_length=255, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('encrypted_access_token', models.TextField(blank=True, default='', help_text='Fernet-encrypted long-lived access token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Expiry timestamp of current access token', null=True)),
                ('token_last_refreshed_at', models.DateTimeField(blank=True, help_text='Timestamp of last token refresh', null=True)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('EXPIRED', 'Token Expired'), ('ERROR', 'Connection Error')], db_index=True, default='CONNECTED', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Last recorded error description if status is ERROR or EXPIRED', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Supplemental account metadata from Graph API (e.g. followers, biography)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_accounts', to='knowledge_base.userprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive automation title', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('ANY_COMMENT', 'Any Comment'), ('KEYWORD_COMMENT', 'Specific Keyword in Comment')], default='KEYWORD_COMMENT', max_length=50)),
                ('target_media_type', models.CharField(choices=[('ALL_POSTS', 'All Posts & Reels'), ('SELECTED_POSTS', 'Specific Posts / Reels')], default='ALL_POSTS', max_length=50)),
                ('keywords', models.JSONField(blank=True, default=list, help_text="List of case-insensitive trigger keywords (e.g. ['price', 'info', 'book'])")),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('CONTAINS', 'Contains Keyword'), ('REGEX', 'Regular Expression')], default='CONTAINS', max_length=50)),
                ('public_reply_enabled', models.BooleanField(default=False, help_text="Whether to post a public reply to the user's comment")),
                ('public_reply_templates', models.JSONField(blank=True, default=list, help_text='Rotating list of public comment replies')),
                ('private_reply_enabled', models.BooleanField(default=True, help_text='Whether to send a private direct message to the commenter')),
                ('private_reply_message', models.TextField(blank=True, help_text='Direct message text content sent to the commenter', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=0, help_text='Evaluation priority order (higher priority evaluated first)')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Runtime statistics (triggers_count, dms_sent, replies_posted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='instagram_integration.instagramaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_automations', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAutomationMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instagram_media_id', models.CharField(db_index=True, help_text='Meta Instagram Media ID', max_length=100)),
                ('media_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('permalink', models.URLField(blank=True, max_length=2000, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_media', to='instagram_integration.instagramautomation')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, help_text='Cryptographically random token', max_length=255, unique=True)),
                ('redirect_uri', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_oauth_states', to='knowledge_base.userprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_oauth_states', to='prospecting.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Unique event deduplication identifier', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g. comments, mentions, messages)', max_length=100)),
                ('sender_id', models.CharField(blank=True, db_index=True, help_text='Instagram-scoped ID of the actor', max_length=100, null=True)),
                ('sender_username', models.CharField(blank=True, max_length=255, null=True)),
                ('media_id', models.CharField(blank=True, db_index=True, help_text='Instagram Media/Post ID', max_length=100, null=True)),
                ('comment_id', models.CharField(blank=True, db_index=True, help_text='Instagram Comment ID if applicable', max_length=100, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Sanitized webhook payload structure')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('IGNORED', 'Ignored'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=50)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='instagram_integration.instagramaccount')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('PUBLIC_REPLY', 'Public Comment Reply'), ('PRIVATE_REPLY', 'Private Direct Message'), ('CRM_RECORD_CREATED', 'CRM Lead Created'), ('CRM_ACTIVITY_LOGGED', 'CRM Activity Logged')], max_length=50)),
                ('recipient_id', models.CharField(db_index=True, help_text='Instagram user ID of the recipient', max_length=100)),
                ('recipient_username', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('media_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key ensuring actions are not duplicated (e.g. comment_id:action_type)', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=50)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='instagram_integration.instagramautomation')),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_actions', to='instagram_integration.instagramaccount')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='instagram_integration.instagramwebhookevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['workspace', 'status'], name='instagram_i_workspa_b7dd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramaccount',
            index=models.Index(fields=['username'], name='instagram_i_usernam_328d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomation',
            index=models.Index(fields=['workspace', 'is_active'], name='instagram_i_workspa_46f18f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomation',
            index=models.Index(fields=['instagram_account', 'is_active'], name='instagram_i_instagr_397b16_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomationmedia',
            index=models.Index(fields=['instagram_media_id'], name='instagram_i_instagr_be1c9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instagramautomationmedia',
            unique_together={('automation', 'instagram_media_id')},
        ),
        migrations.AddIndex(
            model_name='instagramoauthstate',
            index=models.Index(fields=['state', 'is_used'], name='instagram_i_state_9ec723_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramoauthstate',
            index=models.Index(fields=['expires_at'], name='instagram_i_expires_2b7ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['status', 'received_at'], name='instagram_i_status_198bac_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['event_type', 'status'], name='instagram_i_event_t_a8d65f_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['comment_id'], name='instagram_i_comment_d3d270_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramwebhookevent',
            index=models.Index(fields=['media_id'], name='instagram_i_media_i_81c158_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomationaction',
            index=models.Index(fields=['idempotency_key'], name='instagram_i_idempot_9c9a75_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomationaction',
            index=models.Index(fields=['status', 'created_at'], name='instagram_i_status_e7a29b_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramautomationaction',
            index=models.Index(fields=['recipient_id', 'action_type'], name='instagram_i_recipie_3ac8d7_idx'),
        ),
    ]
